### ISSUE TITLE
Minetest messages wont send to discord

### ISSUE THREAD

**Issue by skylord-at-hub** [activivan/mt-dcwebhook#3]
The messages wouldn't send when I was using it, it would only show maintenance messages such as "server has started" or "player1 has joined" but wont show the messages player1 has to send

Edit: some screenshots to show
![image](https://user-images.githubusercontent.com/77268876/229370940-de6b1221-d290-4178-a143-de62570eba0d.png)
![image](https://user-images.githubusercontent.com/77268876/229370984-76dc2d5f-1279-4aeb-8fa4-c1db569a79bd.png)

**Comment by activivan** [comment]
Hi, the mod listens on `minetest.register_on_chat_message`. If you use a custom mod that does not utilize the standard Minetest API or prevents other mods from intercepting messages (by returning `true` to mark the message as handled), your messages might not reach the mt-dcwebhook mod.

**Comment by skylord-at-hub** [comment]
Ah ok, I see the mod "ranks" is causing the problem, maybe you could make "ranks" an optional dependency?
> Hi, the mod listens on `minetest.register_on_chat_message`. If you use a custom mod that does not utilize the standard Minetest API or prevents other mods from intercepting messages (by returning `true` to mark the message as handled), your messages might not reach the mt-dcwebhook mod.

**Comment by activivan** [comment]
Try using the latest release.
