### ISSUE TITLE
French translation & login/out use text instead of embed messages

### ISSUE THREAD

**Issue by Aracaa** [activivan/mt-dcwebhook#5]
I made a patch to add french translation & make the connection/deconnection logs less "big"

Here is an example of what I changed looks like

![image](https://github.com/activivan/mt-dcwebhook/assets/14837771/27212104-865f-4d79-88e1-2175e87314d1)

![image](https://github.com/activivan/mt-dcwebhook/assets/14837771/af56a220-5da2-4bd3-8df9-525fca34e459)

**Comment by activivan** [comment]
French translation and option to customize behaviour included in latest release.
